theme = "blowfish"
baseURL = "https://svspbelagavi.org/"
pluralizeListTitles = "false"
enableRobotsTXT = true
pagerSize = 10
summaryLength = 10
buildDrafts = false
buildFuture = false
# googleAnalytics = "G-PEDMYR1V0K"

[imaging]
  anchor = 'Center'

[taxonomies]

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

# [related]
#  threshold = 0
#  toLower = false
#
#    [[related.indices]]
#        name = "tags"
#        weight = 100
#
#    [[related.indices]]
#        name = "categories"
#        weight = 100
#
#    [[related.indices]]
#        name = "series"
#        weight = 50
#
#    [[related.indices]]
#        name = "authors"
#        weight = 20
#
#    [[related.indices]]
#        name = "date"
#        weight = 10
#
#    [[related.indices]]
#      applyFilter = false
#      name = 'fragmentrefs'
#      type = 'fragments'
#      weight = 10