colorScheme = "fire"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
replyByEmail = false
mainSections = ["events"]
showViews = true
showLikes = true
robots = "all"
disableImageZoom = false
disableImageOptimization = false
disableTextInHeader = true
defaultBackgroundImage = "/img/background2.jpg"
defaultFeaturedImage = "/img/featured.jpg"
highlightCurrentMenuArea = true
smartTOC = false
# smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "/img/background2.jpg"
  showRecent = false
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/donate"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = true 
  showLikes = true
  showDateOnlyInArticle = true
  showDateUpdated = false
  showAuthor = false
  showAuthorBottom = false
  showHero = true
  heroStyle = "thumbAndBackground"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  editURL = false
  editAppendPath = false
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false  # Disabled.
  sharingLinks = [ "whatsapp", "facebook", "linkedin", "twitter", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "thumbAndBackground"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "thumbAndBackground"
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = false
  cardView = true

[term]
  showHero = true
  heroStyle = "thumbAndBackground"
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

# [firebase]

# [fathomAnalytics]

# [buymeacoffee]

# [verification]